//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public int StatusId { get; set; }
        public int TypeId { get; set; }
        public int AreaId { get; set; }
        public Nullable<int> Author { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Event Event { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual Status Status { get; set; }
    }
}
